export const POSTS = {
  LOADING: "POSTS_LOADING",
  LOAD_SUCCESS: "POSTS_LOAD_SUCCESS",
  ERROR: "POSTS_ERROR"
};

export const COMMENTS = {
  ID_POST: "ID_POST_FOR_COMMENTS",
  LOADING: "COMMENTS_LOADING",
  LOAD_SUCCESS: "COMMENTS_LOAD_SUCCESS",
  ERROR: "COMMENTS_ERROR"
};
