export const POSTS = {
  LOADING: "POSTS_LOADING",
  LOAD_SUCCESS: "POSTS_LOAD_SUCCESS",
  ERROR: "POSTS_ERROR"
};

export const COMMENTS = {
  LOADING: "COMMENTS_LOADING",
  LOAD_ERROR: "COMMENTS_ERROR",
  LOAD_SUCCESS: "COMMENTS_LOAD_SUCCESS",
  ID_POST: "ID_POST_FOR_COMMENTS",
  SENDING: "COMMENTS_SENDING",
  SEND_ERROR: "COMMENTS_SEND_ERROR",
  SEND_SUCCESS: "COMMENTS_SEND_SUCCESS",
  SEND: "COMMENTS_SEND"
};
